### ISSUE TITLE
End of Stream Behavior

### ISSUE THREAD

**Issue by krs43** [MiloszKrajewski/K4os.Compression.LZ4#18]
When we reach an end of a stream, but call a read anyways, I would expect to return immediately with a zero bytes return. Instead I either get an exception related to invalid magic number, or End Of Stream Exception. I believe this could be handled in the GetFrame Method, when it asks for a magix number, but instead returns 0/null, it could recognize this is an end of stream and surface a return 0 to the read method.

**Comment by krs43** [comment]
More specifically - if I use Extra Memory, it throws InvalidDataException "LZ4 frame magic number expected", and if I dont use extra memory, I get EndOfStreamException.

**Comment by MiloszKrajewski** [comment]
Definitely looks like a bug. I'll take a look.

**Comment by MiloszKrajewski** [comment]
You are right this is the behaviour. Last read DOES return 0 bytes, but if you try again it with throw.
There is one problem though.
I actually wanted it work that way, to allow appending to possibly finished stream.
Let's imagine that you have regular stream and you closed it, reopened it and started appending. It would form one contiguous stream of bytes.
With LZ4 stream I wanted it to be the same way. So, when you finish writing (and EoS marker is saved), you may start appending new stream. When reading, after end of stream, if you keep reading it just expects new stream to start (LZ4 magic number).

I guess it wasn't really though through and no one was  really asking for it.

I guess this is not as serious as I though though because it does return 0 first time you encounter end of stream.

**Comment by krs43** [comment]
Thanks Milosz - I'll take a closer look again - I didn't realize the first time returned zero successfully. On an unrelated note - do you have any interest in making a C# Zstd library? Current wrappers lack true .net standard suppport, and what you've done for LZ4 has been incredible!

**Comment by MiloszKrajewski** [comment]
Fixed in 1.1.7
